domain: example.com
url: https://example.com
baseurl: "/wind"

title: Wind
email: wind@example.com
author: Wind Sample

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  mood:
    output: true 
    permalink: /mood/:name
  tarot:
    output: true
    permalink: /tarot/:name
  symbol:
    output: true
    permalink: /symbol/:symbol
  8bit:
    output: true
    permalink: /8bit/:name

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope: 
      path: ""
      type: "pages"
    values:
      layout: "mood"
  - scope: 
      path: ""
      type: "pages"
    values:
      layout: "tarot"
  - scope: 
      path: ""
      type: "pages"
    values:
      layout: "8bit"
